# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-scholar

# Site settings
url: 'https://rayolab.netlify.com/'
baseurl: ''
title: 'RayoLab'
description: 'Laboratorio de Neurobiología y Biología del Conocer'
permalink: pretty
logo: "/img/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Inicio: /
  Acerca: /acerca/
  Papers: /papers/
  Blog: /blog/
# Footer nav
navigation_footer:
  Hacia arriba: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Novedades acerca de nuestros proyectos y descubrimientos."
    feature_text: |
      Bienvenido al blog del laboratorio.
    feature_image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7e6ee620a83a58299246d66dd761671e&auto=format&fit=crop"
scholar:
  style: apa